#!/usr/bin/env bash
rm spx_exchange trader_a trader_b trader_c
rm /tmp/spx_*
gcc ./tests/E2E/tradertest.c -o trader_a -g -Wall -Wvla -Werror -fsanitize=address
gcc ./tests/E2E/tradertest1.c -o trader_b  -g -Wall -Wvla -Werror -fsanitize=address
gcc spx_exchange.c -o spx_exchange -g -Wall -Wvla -Werror -fsanitize=address